import { notFound } from "next/navigation";
import { Photo, PhotoData } from "@/components/photo";
import { InquiryLink } from "@/components/navigation";
import { images } from "@/data/photos";

type Story = { name: string; place: string; year: string; hero: PhotoData; chapters: { title?: string; layout: "full" | "pair" | "portrait" | "trio"; photos: PhotoData[] }[] };
const stories: Record<string, Story> = {
 "amanda-and-josh": { name: "Amanda & Josh", place: "Kingston, Jamaica", year: "2026", hero: images.wedding1, chapters: [{ title: "Getting ready", layout: "pair", photos: [images.woman, images.ring] }, { layout: "full", photos: [images.hero] }, { title: "The ceremony", layout: "full", photos: [images.dance] }, { title: "Portraits", layout: "portrait", photos: [images.wedding1, images.palms] }, { title: "The reception", layout: "trio", photos: [images.dinner, images.wedding2, images.sea] }] },
 "sarah-and-daniel": { name: "Sarah & Daniel", place: "Montego Bay, Jamaica", year: "2025", hero: images.wedding2, chapters: [{ title: "On the morning", layout: "pair", photos: [images.woman, images.dinner] }, { layout: "full", photos: [images.palms] }, { title: "By the sea", layout: "portrait", photos: [images.ring, images.sea] }, { title: "The celebration", layout: "trio", photos: [images.dance, images.wedding1, images.hero] }] }
};
export default async function WeddingPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const story = stories[slug]; if (!story) notFound(); return <main className="pt-28"><header className="mx-auto max-w-[1600px] px-5 pb-12 md:px-8 md:pb-16"><p className="eyebrow mb-5 text-[#79756d]">Wedding story</p><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><h1 className="serif text-5xl tracking-[-.045em] md:text-8xl">{story.name}</h1><p className="eyebrow leading-relaxed text-[#79756d]">{story.place}<br />{story.year}</p></div></header><Photo photo={story.hero} priority className="h-[90vw] max-h-[950px] w-full" /><div className="mx-auto max-w-[1600px] space-y-20 px-5 py-20 md:space-y-32 md:px-8 md:py-32">{story.chapters.map((chapter, i) => <StoryLayout key={i} {...chapter} />)}<div className="border-t border-[#c9c5bc] pt-12 text-center md:pt-20"><h2 className="serif text-4xl md:text-6xl">{story.name}</h2><p className="eyebrow mt-4 text-[#79756d]">{story.place} / {story.year}</p><InquiryLink className="eyebrow mt-12 inline-block border-b border-[#12110f] pb-2" /></div></div></main>; }
function StoryLayout({ title, layout, photos }: Story["chapters"][number]) { return <section>{title && <h2 className="eyebrow mb-7 text-[#79756d]">{title}</h2>}{layout === "full" && <Photo photo={photos[0]} className="h-[70vw] min-h-72 max-h-[850px]" />}{layout === "pair" && <div className="grid gap-5 md:grid-cols-2 md:gap-10"><Photo photo={photos[0]} className="h-[115vw] max-h-[780px] md:h-[55vw]" /><Photo photo={photos[1]} className="h-[75vw] min-h-72 md:mt-28 md:h-[40vw]" /></div>}{layout === "portrait" && <div className="grid gap-5 md:grid-cols-[.7fr_1.3fr] md:gap-10"><Photo photo={photos[0]} className="h-[125vw] max-h-[850px] md:h-[62vw]" /><Photo photo={photos[1]} className="h-[65vw] min-h-72 md:mt-44 md:h-[38vw]" /></div>}{layout === "trio" && <div className="grid grid-cols-2 gap-3 md:grid-cols-3 md:gap-6">{photos.map((p, i) => <Photo key={i} photo={p} className={`h-[70vw] min-h-52 md:h-[35vw] ${i === 0 ? "col-span-2 md:col-span-1" : ""}`} />)}</div>}</section>; }
