import Link from "next/link";
import { Photo } from "@/components/photo";
import { InquiryLink } from "@/components/navigation";
import { images } from "@/data/photos";

function Caption({ children }: { children: React.ReactNode }) { return <p className="eyebrow mt-3 text-[#79756d]">{children}</p>; }

export default function Home() {
 return <main>
  <section className="relative h-[100svh] min-h-[620px] bg-[#161512] text-[#f4f1ea]"><Photo photo={images.hero} priority className="absolute inset-0 h-full w-full opacity-90" /><div className="absolute inset-0 bg-black/20" /><div className="relative mx-auto flex h-full max-w-[1600px] items-end px-5 pb-9 md:px-8 md:pb-10"><div className="eyebrow reveal leading-relaxed"><strong>Nathan Crossdale</strong><br />Photographer<br />Jamaica / Caribbean</div><p className="eyebrow absolute bottom-9 right-5 hidden md:block md:right-8">Scroll to explore <span className="ml-1">↓</span></p></div></section>
  <section id="work" className="mx-auto max-w-[1600px] px-5 py-24 md:px-8 md:py-36"><div className="mb-16 flex items-end justify-between"><div><p className="eyebrow mb-4 text-[#79756d]">Selected work</p><h1 className="serif text-4xl tracking-[-.035em] md:text-6xl">Small moments,<br />held close.</h1></div><Link className="eyebrow hidden border-b border-[#12110f] pb-1 md:block" href="/weddings">View wedding stories →</Link></div>
   <div className="space-y-12 md:space-y-24"><Photo photo={images.sea} className="h-[50vw] min-h-72 max-h-[690px] w-full" /><div className="grid gap-5 md:grid-cols-[.85fr_1.15fr] md:items-end md:gap-12"><div><Photo photo={images.woman} className="h-[125vw] max-h-[730px] md:h-[48vw]" /><Caption>Portraits / 2026</Caption></div><div className="md:pb-14"><Photo photo={images.dance} className="h-[65vw] min-h-72 md:h-[42vw]" /><Caption>After the ceremony / Montego Bay</Caption></div></div><div className="grid gap-5 md:grid-cols-[1.25fr_.75fr] md:gap-12"><Photo photo={images.palms} className="h-[65vw] min-h-72 md:h-[44vw]" /><div className="flex items-end"><p className="serif max-w-sm text-2xl leading-tight md:text-4xl">Photographs with a sense of place, and all the feeling that stays after.</p></div></div></div>
  </section>
  <section className="bg-[#1a1916] px-5 py-20 text-[#f4f1ea] md:px-8 md:py-28"><div className="mx-auto max-w-[1600px]"><p className="eyebrow mb-14 text-[#c9c5bc]">Weddings</p><div className="grid gap-12 md:grid-cols-2 md:gap-8"><WeddingFeature href="/weddings/amanda-and-josh" photo="wedding1" title="Amanda & Josh" location="Kingston, Jamaica" year="2026" /><WeddingFeature href="/weddings/sarah-and-daniel" photo="wedding2" title="Sarah & Daniel" location="Montego Bay, Jamaica" year="2025" /></div><Link className="eyebrow mt-14 inline-block border-b border-current pb-1" href="/weddings">All wedding stories →</Link></div></section>
  <section className="mx-auto flex max-w-[1600px] flex-col items-start justify-between gap-10 px-5 py-28 md:flex-row md:items-end md:px-8 md:py-40"><div><p className="eyebrow mb-6 text-[#79756d]">Available throughout Jamaica & beyond</p><h2 className="serif max-w-2xl text-4xl leading-[.98] tracking-[-.04em] md:text-7xl">Let&apos;s make something worth remembering.</h2></div><InquiryLink className="eyebrow border-b border-[#12110f] pb-2" /></section>
 </main>;
}
function WeddingFeature({ href, photo, title, location, year }: { href: string; photo: keyof typeof images; title: string; location: string; year: string }) { return <Link href={href} className="group"><Photo photo={images[photo]} className="h-[115vw] max-h-[760px] md:h-[53vw]" /><div className="mt-4 flex justify-between"><div><h3 className="serif text-2xl">{title}</h3><p className="eyebrow mt-2 text-[#c9c5bc]">{location}</p></div><p className="eyebrow text-[#c9c5bc]">{year}</p></div></Link>; }
